use crate::app::{App, CurrentScreen, InputMode};
use ratatui::{layout::{Constraint, Direction, Layout}, style::{Color, Style, Stylize}, text::{Line, Span}, widgets::{Block, Borders, HighlightSpacing, Paragraph, Row, Table, Wrap}, Frame};

pub fn render(app: &mut App, frame: &mut Frame) {
    let main_layout = Layout::new(Direction::Vertical, [Constraint::Min(0), Constraint::Length(3)]).split(frame.size());
    let top_layout = Layout::new(Direction::Horizontal, [Constraint::Percentage(30), Constraint::Percentage(70)]).split(main_layout[0]);
    let nav_text = "Navegação:\n\n[1] Canto\n[2] Piedade\n[3] Estudo";
    frame.render_widget(Paragraph::new(nav_text).block(Block::default().title("Menu Principal").borders(Borders::ALL)), top_layout[0]);

    match app.current_screen {
        CurrentScreen::SalterioList => { render_salmos_table(app, frame, top_layout[1]); render_salmos_footer(app, frame, main_layout[1]); }
        CurrentScreen::SalmoView => { render_salmo_view(app, frame, top_layout[1]); render_text_view_footer(app, frame, main_layout[1]); }
        // ... outras telas ...
        CurrentScreen::PiedadeMenu => { render_piedade_menu(app, frame, top_layout[1]); render_menu_footer(app, frame, main_layout[1]); }
        CurrentScreen::AcoesList => { render_acoes_list(app, frame, top_layout[1]); render_acoes_footer(app, frame, main_layout[1]); }
        CurrentScreen::ResolucoesList => { render_resolucoes_list(app, frame, top_layout[1]); render_resolucoes_footer(app, frame, main_layout[1]); }
        CurrentScreen::EstudoMenu => { render_estudo_menu(app, frame, top_layout[1]); render_menu_footer(app, frame, main_layout[1]); }
        CurrentScreen::DiarioList => { render_diario_list(app, frame, top_layout[1]); render_diario_list_footer(app, frame, main_layout[1]); }
        CurrentScreen::DiarioView => { render_diario_view(app, frame, top_layout[1]); render_text_view_footer(app, frame, main_layout[1]); }
        CurrentScreen::SymbolsMenu => { render_symbols_menu(app, frame, top_layout[1]); render_symbols_menu_footer(app, frame, main_layout[1]); }
        CurrentScreen::CfwList | CurrentScreen::CmwList | CurrentScreen::BcwList => { if let CurrentScreen::CfwList = app.current_screen { render_cfw_table(app, frame, top_layout[1]); } else if let CurrentScreen::CmwList = app.current_screen { render_cmw_table(app, frame, top_layout[1]); } else { render_bcw_table(app, frame, top_layout[1]); } render_list_view_footer(app, frame, main_layout[1]); }
        CurrentScreen::CfwSections | CurrentScreen::CmwAnswer | CurrentScreen::BcwAnswer => { if let CurrentScreen::CfwSections = app.current_screen { render_cfw_sections(app, frame, top_layout[1]); } else if let CurrentScreen::CmwAnswer = app.current_screen { render_cmw_answer(app, frame, top_layout[1]); } else { render_bcw_answer(app, frame, top_layout[1]); } render_text_view_footer(app, frame, main_layout[1]); }
        CurrentScreen::Biblia => { render_biblia_view(app, frame, top_layout[1]); render_biblia_footer(app, frame, main_layout[1]); }
        CurrentScreen::DiarioNew => {},
    }
    
    if let InputMode::Editing = app.input_mode { frame.set_cursor(main_layout[1].x + app.input.len() as u16 + 1, main_layout[1].y + 1); }
}

// --- Funções de Renderização de Conteúdo ---
fn render_salmo_view(app: &App, frame: &mut Frame, area: ratatui::layout::Rect) {
    if let Some(s) = app.selected_salmo() {
        let text = s.letra.as_deref().unwrap_or("Letra não disponível.");
        let p = Paragraph::new(text).wrap(Wrap { trim: true }).scroll((app.salmo_scroll, 0)).block(Block::default().title(format!("Salmo - {}", s.referencia)).borders(Borders::ALL));
        frame.render_widget(p, area);
    }
}
fn render_salmos_table(app: &mut App, frame: &mut Frame, area: ratatui::layout::Rect) { let h = Row::new(["Ref.", "Melodia"]).style(Style::default().bold()); let r = app.salmos.iter().map(|s| Row::new([s.referencia.clone(), s.melodia.clone().unwrap_or_default()])); let t = Table::new(r, &[Constraint::Percentage(40), Constraint::Percentage(60)]).header(h).block(Block::default().title("Saltério").borders(Borders::ALL)).highlight_style(Style::default().reversed()).highlight_spacing(HighlightSpacing::Always); frame.render_stateful_widget(t, area, &mut app.salmos_state); }
// ... outras funções de renderização ...
fn render_piedade_menu(_app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { frame.render_widget(Paragraph::new("\n [1] Diário\n\n [2] Ações de Santificação\n\n [3] Resoluções").block(Block::default().title("Piedade").borders(Borders::ALL)), area); }
fn render_estudo_menu(_app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { frame.render_widget(Paragraph::new("\n\n   [1] Símbolos de Fé\n\n   [2] Bíblia").block(Block::default().title("Estudo").borders(Borders::ALL)), area); }
fn render_symbols_menu(_app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { let menu_text = "\n   [1] Confissão de Fé\n\n   [2] Catecismo Maior\n\n   [3] Breve Catecismo"; frame.render_widget(Paragraph::new(menu_text).block(Block::default().title("Símbolos de Fé").borders(Borders::ALL)), area); }
fn render_acoes_list(app: &mut App, frame: &mut Frame, area: ratatui::layout::Rect) { let h = Row::new(["", "ID", "Descrição"]).style(Style::default().bold()); let r = app.acoes.iter().map(|a| { let (icon, style) = if a.status == "completo" { ("[✓]", Style::default().fg(Color::Green).dim()) } else { ("[ ]", Style::default()) }; Row::new(vec![Span::styled(icon, style), Span::raw(a.id.to_string()), Span::raw(a.descricao.clone())]).style(style) }); let t = Table::new(r, &[Constraint::Length(3), Constraint::Length(4), Constraint::Min(20)]).header(h).block(Block::default().title("Ações de Santificação").borders(Borders::ALL)).highlight_style(Style::default().reversed()).highlight_spacing(HighlightSpacing::Always); frame.render_stateful_widget(t, area, &mut app.acoes_list_state); }
fn render_resolucoes_list(app: &mut App, frame: &mut Frame, area: ratatui::layout::Rect) { let h = Row::new(["ID", "Texto"]).style(Style::default().bold()); let r = app.resolucoes.iter().map(|r| Row::new([r.id.to_string(), r.texto.clone()])); let t = Table::new(r, &[Constraint::Length(4), Constraint::Min(20)]).header(h).block(Block::default().title("Minhas Resoluções").borders(Borders::ALL)).highlight_style(Style::default().reversed()).highlight_spacing(HighlightSpacing::Always); frame.render_stateful_widget(t, area, &mut app.resolucoes_list_state); }
fn render_diario_list(app: &mut App, frame: &mut Frame, area: ratatui::layout::Rect) { let h = Row::new(["Data", "Início da Entrada"]).style(Style::default().bold()); let r = app.diario_entradas.iter().map(|e| { let p = e.texto.chars().take(80).collect::<String>() + "..."; Row::new([e.data.clone(), p]) }); let t = Table::new(r, &[Constraint::Length(20), Constraint::Min(20)]).header(h).block(Block::default().title("Diário").borders(Borders::ALL)).highlight_style(Style::default().reversed()).highlight_spacing(HighlightSpacing::Always); frame.render_stateful_widget(t, area, &mut app.diario_list_state); }
fn render_diario_view(app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { if let Some(e) = app.selected_diario_entry() { let p = Paragraph::new(e.texto.as_str()).wrap(Wrap { trim: true }).scroll((app.diario_scroll, 0)).block(Block::default().title(format!("Diário - {}", e.data)).borders(Borders::ALL)); frame.render_widget(p, area); } }
fn render_cfw_table(app: &mut App, frame: &mut Frame, area: ratatui::layout::Rect) { let h = Row::new(["Cap.", "Título"]).style(Style::default().bold()); let r = app.cfw_capitulos.iter().map(|c| Row::new([c.chapter.to_string(), c.title.clone()])); let t = Table::new(r, &[Constraint::Length(5), Constraint::Min(20)]).header(h).block(Block::default().title("Confissão de Fé").borders(Borders::ALL)).highlight_style(Style::default().reversed()).highlight_spacing(HighlightSpacing::Always); frame.render_stateful_widget(t, area, &mut app.cfw_list_state); }
fn render_cfw_sections(app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { let text: String = app.cfw_secoes.iter().map(|s| format!("{}. {}\n\n", s.section, s.text)).collect(); let p = Paragraph::new(text).wrap(Wrap { trim: false }).scroll((app.cfw_scroll, 0)).block(Block::default().title(format!("CFW: {}", app.cfw_capitulo_titulo)).borders(Borders::ALL)); frame.render_widget(p, area); }
fn render_biblia_view(app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { let txt = if app.biblia_versiculos.is_empty() { "\n\n\nUse [e] para buscar.".to_string() } else { app.biblia_versiculos.iter().map(|v| format!("[{}] {}\n", v.verse, v.text)).collect() }; let p = Paragraph::new(txt).wrap(Wrap { trim: false }).scroll((app.biblia_scroll, 0)).block(Block::default().title(format!("Bíblia: {}", app.biblia_referencia)).borders(Borders::ALL)); frame.render_widget(p, area); }
fn render_cmw_table(app: &mut App, frame: &mut Frame, area: ratatui::layout::Rect) { let h = Row::new(["Per.", "Pergunta"]).style(Style::default().bold()); let r = app.cmw_perguntas.iter().map(|p| Row::new([p.id.to_string(), p.question.clone()])); let t = Table::new(r, &[Constraint::Length(5), Constraint::Min(20)]).header(h).block(Block::default().title("Catecismo Maior").borders(Borders::ALL)).highlight_style(Style::default().reversed()).highlight_spacing(HighlightSpacing::Always); frame.render_stateful_widget(t, area, &mut app.cmw_list_state); }
fn render_cmw_answer(app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { if let Some(p) = app.selected_cmw_question() { let txt = vec![Line::from(vec![Span::styled("P: ",Style::default().bold().fg(Color::Yellow)),Span::raw(&p.question)]),Line::from(""),Line::from(vec![Span::styled("R: ",Style::default().bold().fg(Color::Yellow)),Span::raw(&p.answer)])]; let par = Paragraph::new(txt).wrap(Wrap { trim: true }).scroll((app.cmw_scroll, 0)).block(Block::default().title(format!("CMW Pergunta {}", p.id)).borders(Borders::ALL)); frame.render_widget(par, area); } }
fn render_bcw_table(app: &mut App, frame: &mut Frame, area: ratatui::layout::Rect) { let h = Row::new(["Per.", "Pergunta"]).style(Style::default().bold()); let r = app.bcw_perguntas.iter().map(|p| Row::new([p.id.to_string(), p.question.clone()])); let t = Table::new(r, &[Constraint::Length(5), Constraint::Min(20)]).header(h).block(Block::default().title("Breve Catecismo").borders(Borders::ALL)).highlight_style(Style::default().reversed()).highlight_spacing(HighlightSpacing::Always); frame.render_stateful_widget(t, area, &mut app.bcw_list_state); }
fn render_bcw_answer(app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { if let Some(p) = app.selected_bcw_question() { let txt = vec![Line::from(vec![Span::styled("P: ",Style::default().bold().fg(Color::Yellow)),Span::raw(&p.question)]),Line::from(""),Line::from(vec![Span::styled("R: ",Style::default().bold().fg(Color::Yellow)),Span::raw(&p.answer)])]; let par = Paragraph::new(txt).wrap(Wrap { trim: true }).scroll((app.bcw_scroll, 0)).block(Block::default().title(format!("BCW Pergunta {}", p.id)).borders(Borders::ALL)); frame.render_widget(par, area); } }

// --- Funções de Renderização de Rodapé ---
fn render_menu_footer(_app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { frame.render_widget(Paragraph::new("Use os números para selecionar ou [v] para voltar.").block(Block::default().title("Ajuda").borders(Borders::ALL)), area); }
fn render_salmos_footer(_app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { frame.render_widget(Paragraph::new("[Enter] Ver Letra | [t] Tocar | [c] Cantar | [s] Parar").block(Block::default().title("Ajuda").borders(Borders::ALL)), area); }
fn render_acoes_footer(app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { let text = match app.input_mode { InputMode::Normal => "[n] Nova | [c] Completar | [p] Pender | [d] Deletar | [v] Voltar", InputMode::Editing => "Nova Ação:", }; frame.render_widget(Paragraph::new(text).block(Block::default().title("Comandos").borders(Borders::ALL)), area); }
fn render_resolucoes_footer(app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { let text = match app.input_mode { InputMode::Normal => "[n] Nova | [d] Deletar | [v] Voltar", InputMode::Editing => "Nova Resolução:", }; frame.render_widget(Paragraph::new(text).block(Block::default().title("Comandos").borders(Borders::ALL)), area); }
fn render_diario_list_footer(_app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { frame.render_widget(Paragraph::new("[n] Nova Entrada | [Enter] Ver | [v] Voltar").block(Block::default().title("Ajuda").borders(Borders::ALL)), area); }
fn render_symbols_menu_footer(_app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { frame.render_widget(Paragraph::new("[1], [2], [3] Selecionar | [v] Voltar").block(Block::default().title("Ajuda").borders(Borders::ALL)), area); }
fn render_list_view_footer(_app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { frame.render_widget(Paragraph::new("[Enter] Ver | [v] Voltar").block(Block::default().title("Ajuda").borders(Borders::ALL)), area); }
fn render_text_view_footer(_app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { frame.render_widget(Paragraph::new("[j/k] Rolar | [v] Voltar").block(Block::default().title("Ajuda").borders(Borders::ALL)), area); }
fn render_biblia_footer(app: &App, frame: &mut Frame, area: ratatui::layout::Rect) { let txt = match app.input_mode { InputMode::Normal => &app.status_message, InputMode::Editing => &app.input }; frame.render_widget(Paragraph::new(txt.as_str()).block(Block::default().title("Comando").borders(Borders::ALL)), area); }
